### PR TITLE
Add components

### PR DESCRIPTION
**Pull request by Alfredbis29**
**In This Milestone I:**

- Delete all the boilerplate from CRA (text, images, styles).
- Create a directory called components.
- Inside components create a new Calculator.js file.
- Develop just the UI of the calculator; the math logic to make it work will be added in the next project.
- Use class-based components (All components should be class-based).

### CODE REVIEW

**Review by t-yanick — CHANGES_REQUESTED** [review]
Hi @Alfredbis29, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

#### I will leave this comments here since they concern files in your repository, and your `readme file` which you haven't made any changes for this `PR`.

- [ ] As it is a [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_components.md) for this project, " `Delete all the boilerplate from CRA (text, images, styles)`", kindly delete all files that are not related to the project. Please checkout your your `public and src` directories and delete all unnecessary file as this will make your repository clean and less crowded. 
- [ ] Please kindly update your `Readme file` to reflect the changes for this milestone, checkout this [template](https://github.com/microverseinc/readme-template) and adapt it your project as this will make your `Readme file` more informative and professional.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alfredbis29** [comment]
Hello @t-yanick, 
Thanks so. much for the professional review. 
Already done with all changements you can now check

**Review by elyor-doniyorov — APPROVED** [review]
Hi @Alfredbis29, 

In my opinion, your project milestone is complete!  There is nothing else to say other than... well done :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Alfredbis29** [comment]
Thanks so much, @elyor-doniyorov  for approval. 
I think I need to move forward to another step. Thanks and happy coding

**Pull request merged**
